version: 0.2
# This file only run the docker file from the indicate folder
phases:
 build:
   commands:
     - echo "Create Docker image for link component in develop workspace..."
     - docker build --no-cache -f config/docker/develop.dockerfile .
     - echo "Porccess finished."