version: 0.2
# This file only run the docker file from the indicate folder
phases:
 build:
   commands:
     - echo "Create Docker image for publish component..."
     - docker build --no-cache -f config/docker/master.dockerfile .
     - echo "Porccess finished."